name: webview_flutter_platform_interface
description: A common platform interface for the webview_flutter plugin.
repository: https://github.com/flutter/packages/tree/main/packages/webview_flutter/webview_flutter_platform_interface
issue_tracker: https://github.com/flutter/flutter/issues?q=is%3Aissue+is%3Aopen+label%3A%22p%3A+webview_flutter%22
# NOTE: We strongly prefer non-breaking changes, even at the expense of a
# less-clean API. See https://flutter.dev/go/platform-interface-breaking-changes
version: 2.0.2

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface:
    git:
      url: https://github.com/Ahmed3mad/webview_upgrade
      path: plugins-packages-plugin_platform_interface
      ref: main
