name: webview_flutter
description: A Flutter plugin that provides a WebView widget on Android and iOS.
repository: https://github.com/flutter/packages/tree/main/packages/webview_flutter/webview_flutter
issue_tracker: https://github.com/flutter/flutter/issues?q=is%3Aissue+is%3Aopen+label%3A%22p%3A+webview%22
version: 4.0.5

environment:
  sdk: ">=2.7.0 <3.0.0"

flutter:
  plugin:
    platforms:
      android:
        default_package: webview_flutter_android
      ios:
        default_package: webview_flutter_wkwebview

dependencies:
  flutter:
    sdk: flutter
  webview_flutter_android:
    git:
      url: https://github.com/Ahmed3mad/webview_upgrade
      path: packages-packages-webview_flutter-webview_flutter_android
      ref: main
  webview_flutter_platform_interface:
    git:
      url: https://github.com/Ahmed3mad/webview_upgrade
      path: packages-packages-webview_flutter-webview_flutter_platform_interface
      ref: main
  webview_flutter_wkwebview:
    git:
      url: https://github.com/Ahmed3mad/webview_upgrade
      path: packages-packages-webview_flutter-webview_flutter_wkwebview
      ref: main
  plugin_platform_interface:
    git:
      url: https://github.com/Ahmed3mad/webview_upgrade
      path: plugins-packages-plugin_platform_interface
      ref: main

dev_dependencies:
  
